hydra:
  run: 
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

defaults:
  - _global_/dataset@_global_
  - _global_/prefix@_global_
  # different config for 
  - train: vitpose_vitpool_tconv_trans
  # - eval: default

