#@package _global_
defaults:
  - /_global_/prefix@_global_
  - /resources@_global_
  - /hydra: no_output
  - /engines: defaults
  - /optimizer: adam
  - /lr_scheduler: multistep
  - /data/dataset: ph14
  - /data/loader: defaults
  - /transforms/train: 192x192
  - /transforms/test: 192x192
  - /model: resnet_lstm
  - /loss: vac
  
seed: 3407
epoch: 90
output_dir: 

#if continuos read model
load_weights: False
is_resume: False
checkpoint: outputs/train/2024-03-28_03-09-56/checkpoint.pt

data_excluded: ["13April_2011_Wednesday_tagesschau_default-14",]
  
data:
  loader:
    train: 
      batch_size: 2
      num_workers: 6
      shuffle: false
    val:
      batch_size: 2

optimizer:
  lr: 1e-4

lr_scheduler:  
  milestones: [20, 40, 55, 70, 80, 90]
  gamma: 0.5
