#@package _global_
defaults:
  - /prefix@_global_
  - /resources@_global_
  - /hydra: no_output
  - /datamodule: ph14
  - /optimizer: adam
  - /lr_scheduler: step
  - /transforms/train: 192x192
  - /transforms/test: 192x192
  - /model: resnet_trans
  - /loss: vac
  
seed: 3407
epoch: 200
tags: 
  - resnet_trans
  - pytorch_lightning

#-1 when we don want message out

#if continuos read model
load_weights: False
is_resume: False
checkpoint: outputs/train/2024-03-28_03-09-56/checkpoint.pt

data_excluded: ["13April_2011_Wednesday_tagesschau_default-14",]
  
datamodule:
  batch_size: 1
  num_workers: 6
  train_shuffle: False

optimizer:
  lr: 1e-4


lr_scheduler:  
  step_size: 40
  gamma: 0.1
