#@package _global_
defaults:
  - /_global_/dataset@_global_
  - /_global_/prefix@_global_
  # - override hydra/hydra_logging: disabled
  # - override hydra/job_logging: disabled
  - /hydra: no_output
  - /engines: defaults
  - /optimizer: adam
  - /lr_scheduler: multistep
  - /data/dataset: ph14
  - /data/loader: defaults
  - /transforms/train: defaults
  - /transforms/test: defaults
  - /model: resnet_trans
  - /loss: vac
  
seed: 3407
epoch: 85
output_dir: 

#-1 when we don want message out
message_interval: 100
vocab_size: 1296

#if continuos read model
load_weights: False
is_resume: False
checkpoint: outputs/train/2024-03-28_03-09-56/checkpoint.pt

data_excluded: ["13April_2011_Wednesday_tagesschau_default-14",]
  
data:
  loader:
    train: 
      batch_size: 4
      num_workers: 4
      shuffle: false
    val:
      batch_size: 1

optimizer:
  lr: 1e-4

lr_scheduler:  
  milestones: [20, 40, 50, 50]
  gamma: 0.5
