#@package _global_
defaults:
  - /_global_/prefix@_global_
  - /resources@_global_
  - /hydra: no_output
  - /engines: defaults
  - /optimizer: adam
  - /lr_scheduler: multistep
  - /data/dataset: ph14
  - /data/loader: defaults
  - /transforms/train: 192x192
  - /transforms/test: 192x192
  - /model: vitpose_trans
  - /loss: vac
  
seed: 3407
device: cuda
epoch: 90
  
snap_path: snap

#-1 when we don want message out
message_interval: 100
vocab_size: 1296

#if continuos read model
load_weights: False
checkpoint: outputs/train_ddp/2024-04-06_05-59-20/checkpoint.pt

data_excluded: ["13April_2011_Wednesday_tagesschau_default-14",]
  
data:
  loader:
    train: 
      batch_size: 1
      num_workers: 6
      shuffle: false
    val:
      batch_size: 1

optimizer:
  lr: 1e-5

lr_scheduler:  
  milestones: [20, 40, 55, 65, 75, 80, 85, 90]
  gamma: 0.5
