#@package _global_
defaults:
  - /_global_/prefix@_global_
  - /resources@_global_
  - /hydra: no_output
  - /engines: defaults
  - /optimizer: adam
  - /lr_scheduler: multistep
  - /data/dataset: ph14
  - /data/loader: defaults
  - /transforms/train: 192x192
  - /transforms/test: 192x192
  - /model: vitpose_vitpool_tconv_convformer
  - /loss: vac
  
seed: 3407
device: cuda
epoch: 40
  
snap_path: snap

#-1 when we don want message out
message_interval: 100
vocab_size: 1296

#if continuos read model
load_weights: True
checkpoint: /home/jingyan/Documents/sign_language_rgb/outputs/train_ddp/2024-04-08_19-50-22/checkpoint.pt
  

data_excluded: ["13April_2011_Wednesday_tagesschau_default-14",]
  
data:
  loader:
    train: 
      batch_size: 1
      num_workers: 4
      shuffle: false
    val:
      batch_size: 1

optimizer:
  lr: 1e-6

# lr_scheduler:  
#   milestones: [20, 40, 55, 65, 75, 80, 85, 90]
#   gamma: 0.5

lr_scheduler:  
  milestones: [100]
  gamma: 0.5
