#@package _global_
defaults:
  - /_global_/prefix@_global_
  - /resources@_global_
  - /hydra: no_output
  - /engines: defaults
  - /optimizer: adam
  - /lr_scheduler: multistep
  - /datamodule: ph14
  - /transforms/train: 192x192
  - /transforms/test: 192x192
  - /model: x3d_tconv_lstm
  - /loss: vac
  
seed: 3407
epoch: 80
output_dir: 

#-1 when we don want message out
message_interval: 100
vocab_size: 1296

#if continuos read model
load_weights: False
is_resume: False
checkpoint: outputs/train_lightning/2024-04-11_22-49-43/last.ckpt

data_excluded: ["13April_2011_Wednesday_tagesschau_default-14",]
  
datamodule:
  batch_size: 2

optimizer:
  lr: 2e-4

lr_scheduler:  
  milestones: [30, 50, 60, 70, 80, 90]
  gamma: 0.2
