csi: csi_sign_language
transform: torchvision.transforms
T: torchvision.transforms
CT: csi_sign_language.data.transforms

phoenix14_root: /home/jingyan/Documents/sign_language_rgb/preprocessed/ph14
device: cuda
verbose: True

checkpoint: /home/jingyan/Documents/sign_language_rgb/outputs/2024-01-15/14-45-57/checkpoint.pt

model:
  _target_: ${csi}.models.models.ResnetTransformer
  d_feedforward: 1024
  n_head: 2
  n_class: 1296


inferencer:
  _target_: ${csi}.engines.inferencers.Inferencer
  device: ${device}
  num_class: 1296

data:
  subset: multisigner
  collate_fn: 
    _target_: ${csi}.data.dataset.phoenix14.CollateFn
  video_transform: 
        _target_: ${T}.Compose
        transforms: 
        - _target_: ${CT}.video.FrameScale
        - _target_: ${CT}.video.ToTensor
  test_set: 
    _target_: ${csi}.data.dataset.phoenix14.MyPhoenix14Dataset
    data_root: ${phoenix14_root}
    subset: ${data.subset}
    mode: test
    transform: ${data.video_transform}


  test_loader:
    _target_: torch.utils.data.DataLoader
    batch_size: 2
    num_workers: 12
    dataset: ${data.test_set}
    collate_fn: ${data.collate_fn}
