csi: csi_sign_language
transform: torchvision.transforms
T: torchvision.transforms
CT: csi_sign_language.data.transforms

seed: 3407
phoenix14_root: /home/jingyan/Documents/sign_language_rgb/preprocessed/ph14_lmdb
vocab_dir: /home/jingyan/Documents/sign_language_rgb/dataset/pheonix14-multi-vocab.txt
device: cuda
verbose: True
epoch: 50

#if continuos read model
is_resume: False
checkpoint: /home/jingyan/Documents/sign_language_rgb/outputs/2024-01-15/14-14-11/checkpoint.pt
  

model:
  _target_: ${csi}.models.models.ResnetTransformer
  d_feedforward: 1024
  n_head: 2
  n_class: 1296

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.LambdaLR
  lr_lambda: 
    _target_: ${csi}.utils.lr_scheduler.WarmUpLr
    initial_lambda: 0.1
    warm_up_rounds: 2
  
trainner:
  _target_: ${csi}.engines.trainers.Trainner
  num_class: 1296
  device: ${device}
  verbose: ${verbose}

inferencer:
  _target_: ${csi}.engines.inferencers.Inferencer
  device: ${device}
  num_class: 1296

data:
  subset: multisigner
  collate_fn: 
    _target_: ${csi}.data.dataset.phoenix14.CollateFn
  video_transform: 
        _target_: ${T}.Compose
        transforms: 
        - _target_: ${CT}.video.FrameScale
        - _target_: ${CT}.video.ToTensor
    
  train_set: 
    _target_: ${csi}.data.dataset.phoenix14.MyPhoenix14Dataset
    data_root: ${phoenix14_root}
    subset: ${data.subset}
    mode: train
    transform: ${data.video_transform}

  val_set: 
    _target_: ${csi}.data.dataset.phoenix14.MyPhoenix14Dataset
    data_root: ${phoenix14_root}
    subset: ${data.subset}
    mode: dev
    transform: ${data.video_transform}


  train_loader:
    _target_: torch.utils.data.DataLoader
    batch_size: 2
    num_workers: 6
    pin_memory: True
    dataset: ${data.train_set}
    collate_fn: ${data.collate_fn}

  val_loader:
    _target_: torch.utils.data.DataLoader
    batch_size: 2
    num_workers: 12
    dataset: ${data.val_set}
    collate_fn: ${data.collate_fn}


