csi: csi_sign_language
transform: torchvision.transforms
T: torchvision.transforms
CT: csi_sign_language.data.transforms

phoenix14_root: /home/jingyan/Documents/sign_language_rgb/preprocessed/ph14
vocab_dir: /home/jingyan/Documents/sign_language_rgb/dataset/pheonix14-multi-vocab.txt
device: cuda
debug: True
epoch: 50

model:
  _target_: ${csi}.models.models.ResnetTransformer
  d_feedforward: 1024
  n_head: 2
  n_class: 1296

video_transform: 
      _target_: ${T}.Compose
      transforms: 
      - _target_: ${CT}.video.FrameScale
      - _target_: ${CT}.video.ToTensor

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-5
  
trainner:
  _target_: ${csi}.engines.trainers.Trainner
  num_class: 1296
  device: ${device}
  debug: True

data:
  category: multisigner
  collate_fn: 
    _target_: ${csi}.data.dataset.phoenix14.CollateFn

  train_set: 
    _target_: ${csi}.data.dataset.phoenix14.MyPhoenix14Dataset
    data_root: ${phoenix14_root}
    category: ${data.category}
    subset: train
    transform: ${video_transform}

  val_set: 
    _target_: ${csi}.data.dataset.phoenix14.MyPhoenix14Dataset
    data_root: ${phoenix14_root}
    category: ${data.category}
    subset: dev
    transform: ${video_transform}


  train_loader:
    _target_: torch.utils.data.DataLoader
    batch_size: 2
    num_workers: 12
    dataset: ${data.train_set}
    collate_fn: ${data.collate_fn}

  val_loader:
    _target_: torch.utils.data.DataLoader
    batch_size: 2
    num_workers: 12
    dataset: ${data.val_set}
    collate_fn: ${data.collate_fn}


